services:
  typescript-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: typescript-app
    restart: unless-stopped
    init: true
    env_file: ./.env
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/cookai
      WATCHPACK_POLLING: true
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - db
    networks:
      - appnet

  db:
    image: postgres:latest
    container_name: cookai_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cookai
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - appnet

  adminer:
    image: adminer:latest
    container_name: cookai_adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  postgres_data:
